FROM maxpeal/x2go:latest
MAINTAINER Max Peal

ENV DEBIAN_FRONTEND noninteractive

# Install Lubuntu  suite
#RUN apt-get update -y && apt-get install -y Lubuntu-desktop --install-recommends
RUN apt-get update -y && apt-get install -y lubuntu-desktop

