FROM maxpeal/x2go
MAINTAINER Max Peal

ENV DEBIAN_FRONTEND noninteractive

# Install KDE suite
#RUN apt-get update -y && apt-get install -y plasma-desktop
#RUN apt-get update -y && apt-get install -y plasma-desktop --install-recommends
RUN apt-get update -y && apt-get install -y kubuntu-desktop

