FROM maxpeal/x2go
MAINTAINER Max Peal

ENV DEBIAN_FRONTEND noninteractive

#Install xubuntu desktop for XFCE
#RUN apt-get update -y && apt-get install -y xubuntu-desktop
RUN apt-get update -y && apt-get install -y xubuntu-desktop --install-recommends
